[package]
name = "run"
version = "0.1.0"
edition = "2018"

[dependencies]
wasm-run = { version = "0.8.1" }
structopt = "0.3"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

[workspace]
members = ["yewprint", "yewprint-doc"]
