[package]
name = "yewprint"
version = "0.1.0"
authors = ["Cecile Tonglet <cecile.tonglet@cecton.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tree"]
tree = ["id_tree"]

[badges]
travis-ci = { repository = "cecton/yewprint", branch = "main" }
is-it-maintained-issue-resolution = { repository = "cecton/yewprint" }
is-it-maintained-open-issues = { repository = "cecton/yewprint" }

[dependencies]
yew = "0.17.4"
web-sys = "0.3"
id_tree = { version = "1.7", optional = true }
yewtil = { version = "0.3.2", features = ["pure"] }

[build-dependencies]
regex = { version = "1", default-features = false, features = ["std"] }
heck = "0.3"
