name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: rustfmt
      if: ${{ github.event_name == 'pull_request' }}
      run: rustfmt --check **/*.rs
    - name: Clippy
      if: ${{ github.event_name == 'pull_request' }}
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests (with all features, including "doc")
      run: cargo test --all-features --verbose
    - name: Rustdoc (without feature "doc")
      run: cargo doc --verbose
