name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: rustfmt
      if: ${{ github.event_name == 'pull_request' }}
      run: rustfmt --check **/*.rs
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features -- -D warnings
    - name: Run tests (with all features, including "doc")
      run: cargo test --all-features --verbose
    - name: Rustdoc (without feature "doc")
      run: cargo doc --verbose
    - name: Build (release)
      if: ${{ github.event_name == 'pull_request' }}
      run: cargo build --release
    - name: Get total wasm size
      if: ${{ github.event_name == 'pull_request' }}
      run: ls public
    - name: Checkout main
      if: ${{ github.event_name == 'pull_request' }}
      run: git checkout main
    - name: Build (release)
      if: ${{ github.event_name == 'pull_request' }}
      run: cargo build --release
    - name: Get total wasm size
      if: ${{ github.event_name == 'pull_request' }}
      run: du -h public/wasm_bg.wasm >> output
    - name: Comment results
      if: ${{ github.event_name == 'pull_request' }}
      uses: amn41/comment-on-pr@comment-file-contents
      #if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: output
